### ISSUE TITLE
Organize code in a package

### ISSUE THREAD

**Issue by Overdrivr** [getlogbook/logbook#194]
I am in the process of adding logging to a package. Ideally, I would like to:
* make call logs inside the package
* assign handlers to loggers outside the package

I have a specific log channel that I need to redirect to a specific handler.

I read the docs but I cannot visualise in my head the overall structure.

What would be the smart way to go about this thing ?

**Comment by vmalloc** [comment]
In general, Logbook is very different from the built-in `logging` package in that it doesn't assign handlers to loggers. Loggers are mere channels that can be turned on or off, all leading to a single handler stack.

You can have handlers that only listen to specific channels via filters, if that's what you want, but in order to block records from all channels except for one, there is no elegant solution for that at the moment.

**Comment by Overdrivr** [comment]
Ok, thanks for the feedback. Built-in `logging` seems more suited for my need here.
