### ISSUE TITLE
New Release With ContextVars Support

### ISSUE THREAD

**Issue by iwoloschin** [getlogbook/logbook#294]
Is there any chance that a new release (1.5?) could be cut including #290 now that it's merged?  If not, is there a roadmap for additional items that must be completed before release (aka, what can I do to help)?

Thanks!

**Comment by vmalloc** [comment]
I will release one today. However I have no time to actually test it in real use, so I'd appreciate help in spotting possible regressions

**Comment by iwoloschin** [comment]
I did one very brief test that worked fine, with both `threadbound` and `contextbound` logging, but it's hardly a fully regression test suite.

**Comment by iwoloschin** [comment]
I think the release may have overwritten the 1.4.3 release?  Also, the source tarball wasn't upgraded (which I believe I need as I'm installing into an Alpine container).

**Comment by vmalloc** [comment]
I don't know about the 1.4.3 tag being overwritten -- I was the one who released it AFAIR and I didn't change the tag locally...

About the sdist, I think there is a problem with pypi deployment on Travis. I moved several repos of mine to use twine instead of travis deploy which is crap, but I don't have time to do it for Logbook as well right now. I'm uploading the release manually, and hopefully will get to fix the automated deployment soon. Sorry for the hassle...

**Comment by vmalloc** [comment]
Ok, I think I understand what happened here... I'm going to have to re-release 1.4.3 to fix it

**Comment by vmalloc** [comment]
Hopefully everything should be fine now. I fixed the Travis deployment debacle, deleted the bad 1.4.3 release and released 1.5.2 which should be good.
Unfortunately one cannot re-upload a past release so I released 1.4.4 to replace 1.4.3 in the 1.4.x release line...
Let me know if there are still issues needing attention. Thanks!
