### ISSUE TITLE
Release 1.4.3 is gone

### ISSUE THREAD

**Issue by danielhers** [getlogbook/logbook#295]
```
$ pip install logbook==1.4.3

Could not find a version that satisfies the requirement logbook==1.4.3 (from versions: 0.1, 0.2, 0.2.1, 0.3, 0.4, 0.4.1, 0.4.2, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 1.0.0, 1.1.0, 1.2.1, 1.2.2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.4.3.post1, 1.4.4, 1.5.1, 1.5.2)
```
I just updated the `logbook` version in [my project](https://github.com/huji-nlp/tupa) to 1.5.2, but unfortunately, previous tagged versions (also released on PyPI) actually pin the version to 1.4.3, so now they all fail installation.

Any chance 1.4.3 can be brought back? Are there any other steps I can take as a solution to the problem except going back to all my tagged versions, unpinning the `logbook` version (changing `==` to `>=`) and creating new releases?

**Comment by vmalloc** [comment]
Unfortunately that is correct. Due to an issue I don't fully understand the release got corrupted this morning (Travis builds were very erratic, and I think somehow pypi allowed uploading newer code under the 1.4.3 name). I wasn't able to re-upload the correct release, so I had to delete it to avoid breaking things for lots of people.

I published both 1.5.2 and 1.4.4, the latter replacing 1.4.3 for people not wanting to move to 1.5 for some reason.

Once again - this is my bad (amplified by Travis, but still) and I deeply apologize...

I'm leaving this issue open and pinned so that people can know what happened and avoid opening duplicates

**Comment by danielhers** [comment]
Thanks, @vmalloc, for the quick response. I'll make sure to avoid pinning to a specific version from now on...

**Comment by vmalloc** [comment]
@danielhers I understand this is not always possible (e.g. lockfiles) but when it is, you can use `<1.5` -- Logbook follows SemVer so that ensures you get the latest bugfixes without making the jump to new functionality or breaking changes

**Comment by prometheanfire** [comment]
Even bad releases should not be removed as it breaks others CI.  I know you can't re-upload the release (and have a post1 version up now), but in the future just do the post1 release and move on.

**Comment by prometheanfire** [comment]
see https://review.opendev.org/677730 for downstream impact.

**Comment by vmalloc** [comment]
First, I once again apologize for that. I made a call given a quick experiment I made showed that using == did not pick up the post release in my environment, which is what triggered my decision to remove it. 

I’ll avoid it in the future of course, but the way I see it pypi is at fault here. Either corrupting an existing release should be impossible, or re-uploading a release to fix it should be possible.

**Comment by prometheanfire** [comment]
true, though that doesn't excuse the removal imo.  have you raised the pypi issue upstream?

**Comment by vmalloc** [comment]
For anyone coming here to scold me and make me feel bad (or feeling better with themselves for making me feel worse) - there's really no need. I already feel pretty bad about what happened, I realize I made a mistake, and of course understand the impacts of removing releases. I understood it before as well, I just made a bad call when weighing risks. It happens to many people, myself included.

I'm pretty much the only active maintainer left for this project, even though I'm not actively using it in my day to day work anymore. I do it on my free time, including when I really have no time for it.

I am taking responsibility over my actions (and mistakes). I apologized. several times, and also in DMs with several people. I left this issue open and pinned so that everyone can read and know what I've done by mistake. There's really no need to kick me when I'm down.

**Comment by vmalloc** [comment]
And to answer @prometheanfire, I am still trying to figure out what exactly went wrong with the original push. I think the issue was that the 1.4.3 travis build has been broken long ago, and we fixed it in develop. Then the 1.5.0 release contained version 1.4.3 internally, which made it upload a release for 1.4.3. That is the part I'm still not 100% sure why worked, because a working release existed for 1.4.3. I will try to see if I have enough for pypa to work with, and if so I'll contact them.

**Comment by prometheanfire** [comment]
sounds good, thanks

**Comment by ovianao** [comment]
@vmalloc, thanks for supporting on your free time. :+1:
